### ISSUE TITLE
Feature request: 3 levels of granularity

### ISSUE THREAD

**Issue by mikeprecious** [KevinWoodhouse/sketch-nudged#1]
Feature request: 3 levels of granularity

Level 1: Left right arrow keys (use case: 1px shift increment, more or less, fine tuning oriented) 

Level 2: Shift + left right arrow keys (use case: 8px shift increment)

Level 3: Opt+Shift+ left right arrow keys (use case: 24px shift increment)

The more coarse shift with Level 3 would be for instances where you're attempting move major elements into place with left right edge margin spaces for example. 

Appreciate your contributions with this plugin!

**Comment by KevinWoodhouse** [comment]
Yep this is a feature I want to add in the future.

I feel like Level 3 should use Ctrl + Shift + Arrow keys. 
Because Opt should remain default key modifier to show the measurement data on screen while nudging.

**Comment by mikeprecious** [comment]
Sounds good!

Do you know roughly when, the Level 3 control feature may get teed up in the feature queue?

**Comment by illustree** [comment]
cool! that is really what is missing and why I until today (Sketch 43) used Sketch-nudge legacy plugin where I was able to use the normal 1, 10 and additionally a CUSTOM value ... since legacy is not available any longer I am counting on you now ;--) many thanks in advance

**Comment by KevinWoodhouse** [comment]
Hi Mike & Dimitri,

Thanks for the feedback. 
The Latest version of Nudged 2.0 was just launched…

I’ve added a “_Custom Nudge_” input which gives you 3 levels of control.
Key Shortcut : ( ctrl + alt + arrow keys )

2.0 also includes a lot of UI and workflow enhancements, go check it out and download from the [Nudged Website](https://kevinwoodhouse.github.io/sketch-nudged/)

Thanks
