### ISSUE TITLE
Settings not opening when selecting from the drop down

### ISSUE THREAD

**Issue by aruffo3** [KevinWoodhouse/sketch-nudged#12]
When I select the Nudge Settings from the plug in drop down, nothing happens.

Sketch version 49.1

Exception: {
    line = 256;
    sourceURL = "/Users/vsra97/Library/Application Support/com.bohemiancoding.sketch3/Plugins/sketch-nudged.sketchplugin/Contents/Sketch/nudged.cocoascript";
}

**Comment by KevinWoodhouse** [comment]
Hi aruffo3,
Thanks for your report, are you able to provide some more info to help me debug.

What version of Nudged are you using?
Is it a fresh install of Nudged?
Was Nudged previously working and now stopped?
Did you download Nudged from GIthub/Gumroad or install via Runner/other? 
Did you upgrade / disable / enable any other plugins beforehand?
