### ISSUE TITLE
Can't apply new nudge settings

### ISSUE THREAD

**Issue by justpickausername** [KevinWoodhouse/sketch-nudged#17]
### Subject of the issue
When clicking on Apply nothing happens.

### Your environment
* version of MacOS 10.15.5
* version of Sketch 66.1
* version of Nudged 2.0.2

### Recent changes to your environment
Probably MacOS update and Sketch update

### Nudged Install
Tell is where you downloaded and installed Nudged from? 
Github

### Steps to reproduce
Open Nudge. Change nudge settings that I need. Click apply. 

### Expected behaviour
Nudge window should close after clicking apply and new settings should be applied.

### Actual behaviour
After clicking Apply nothing happens.

### ScreenShots of issue
---

### Error messages or logs
---

**Comment by KevinWoodhouse** [comment]
Hi,
Thank you for posting this issue.
I'm investigating this bug and will try to offer a fix/update as soon as possible.

**Comment by stesmiffy** [comment]
Hi Kev. I too have been experiencing this problem with the latest version of Sketch. It defaults the values back rather than retaining them.

**Comment by KevinWoodhouse** [comment]
Fixed in [v2.1](https://github.com/KevinWoodhouse/sketch-nudged/archive/v2.1.zip)

**Comment by stesmiffy** [comment]
Awesome! Thanks Kev!
