### ISSUE TITLE
first inputfield should be active directly when opening plugin

### ISSUE THREAD

**Issue by illustree** [KevinWoodhouse/sketch-nudged#4]
I think this is a quick one, could you please add this functionality? so that I could trigger plugin and directly add a number and hit ENTER

**Comment by KevinWoodhouse** [comment]
Hi Dimitri,

Thanks for the feedback. 
Fixed in the Latest version of Nudged 2.0.

Check it out and download from the [Nudged Website](https://kevinwoodhouse.github.io/sketch-nudged/)

Thanks
