### ISSUE TITLE
reset values shortcut

### ISSUE THREAD

**Issue by illustree** [KevinWoodhouse/sketch-nudged#5]
once I set the first value, normally I would use it for 2,3 steps .. moving and aligning elements – and that's it --->  then I always have to go back to the standard 1/10 px values ... so if there was a shortcut for resetting - it would be just awesome and would improve the workflow a lot

thx in advance
Dimitri

**Comment by KevinWoodhouse** [comment]
Hi Dimitri,

Thanks for the feedback. 
The Latest version of Nudged 2.0 was just launched…

Adding a ‘Reset Nudge settings to Defaults’ global shortcut ( ctrl + alt + 0 ) and the UI now features a reset button while editing. 

Check it out and download from the [Nudged Website](https://kevinwoodhouse.github.io/sketch-nudged/)

Thanks
